[build-system]
requires = [
    'ipykernel',
    'pandas',
    'numpy',
    'jupyter >= 1.0.0',
    'matchms >= 0.9.0',
    'spec2vec >= 0.4',
    'plotly >= 4.14.3',
    'cimcb-lite >= 1.0.2',
    'scikit-learn >= 0.24.1'
]
build-backend = "setuptools.build_meta"