name: memo_examples_env
channels:
  - conda-forge
  - bioconda
  - defaults
  - anaconda
dependencies:
  - python==3.7
  - numpy
  - pandas
  - scipy
  - umap-learn
  - plotly
  - pip
  - pip :
    - memo_ms
    - datatable
    - scikit-bio