name: integration-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  memo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          conda install -c conda-forge scikit-bio
          python -mpip install numpy
          pip install .
      - name: Run Notebook
        uses: yaananth/run-notebook@v1
        env:
          RUNNER: ${{ toJson(runner) }}
          SECRETS: ${{ toJson(secrets) }}
          GITHUB: ${{ toJson(github) }}
        with:
          notebook: "tutorial_memo.ipynb"
          # params: "parameters.json"
          isReport: False
      - name: Run tests
        run: |
          bash tests/integration_test.sh
