name: integration-test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  memo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          conda install -c conda-forge scikit-bio
          python -mpip install numpy
          pip install .
          pip install papermill ipykernel
      - name: Execute Notebook
        run: |
          papermill tutorial_memo.ipynb tutorial_memo.ipynb
      - name: Run tests
        run: |
          bash tests/integration_test.sh
