name: Python Package using Conda

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  memo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          $CONDA/bin/conda create -n memo python=3.8
          $CONDA/bin/conda init powershell
          $CONDA/bin/conda activate memo
          pip install .
      - name: Run tests
        run: |
          bash tests/integration_test.sh
